// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbj3lg5FD9ytk8t6p2vqEm9EodjNtjM5E',
    appId: '1:638778848216:web:683abc3c81fab6459d38ad',
    messagingSenderId: '638778848216',
    projectId: 'bip-projects',
    authDomain: 'bip-projects.firebaseapp.com',
    storageBucket: 'bip-projects.firebasestorage.app',
    measurementId: 'G-BLG8K38C7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpdpVYDvt0nXKoRIRZN6oQW8s-KHPBfmk',
    appId: '1:638778848216:android:e7c9d57a3f1a040a9d38ad',
    messagingSenderId: '638778848216',
    projectId: 'bip-projects',
    storageBucket: 'bip-projects.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAljS83XEl8Sh19n4ohOZlD-VVdBx5yr-8',
    appId: '1:638778848216:ios:d1d88911e2b1da279d38ad',
    messagingSenderId: '638778848216',
    projectId: 'bip-projects',
    storageBucket: 'bip-projects.firebasestorage.app',
    iosClientId: '638778848216-9117ngdon8bt0e879d8a01dks82n1hdu.apps.googleusercontent.com',
    iosBundleId: 'com.fsktm.jembalangCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAljS83XEl8Sh19n4ohOZlD-VVdBx5yr-8',
    appId: '1:638778848216:ios:d1d88911e2b1da279d38ad',
    messagingSenderId: '638778848216',
    projectId: 'bip-projects',
    storageBucket: 'bip-projects.firebasestorage.app',
    iosClientId: '638778848216-9117ngdon8bt0e879d8a01dks82n1hdu.apps.googleusercontent.com',
    iosBundleId: 'com.fsktm.jembalangCounter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbj3lg5FD9ytk8t6p2vqEm9EodjNtjM5E',
    appId: '1:638778848216:web:136a82c14186b36e9d38ad',
    messagingSenderId: '638778848216',
    projectId: 'bip-projects',
    authDomain: 'bip-projects.firebaseapp.com',
    storageBucket: 'bip-projects.firebasestorage.app',
    measurementId: 'G-X8C12WC06D',
  );
}
